version: '3.8'

services:
  frontend:
    build: .
    container_name: ecommerce-analysis-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - ecommerce-network

  # 如果将来需要添加后端服务，可以在这里添加
  # backend:
  #   image: your-backend-image
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
